language: cpp
before_script:
- sudo apt-get install libboost-test-dev -y
- sudo apt-get install cmake
- cd /usr/src/gtest
- sudo cmake CMakeLists.txt
- sudo cp *.a /usr/lib
- sudo mkdir -P /usr/local/lib/googletest
- sudo ln -s /usr/lib/libgtest.a /usr/local/lib/gtest/libgtest.a
- sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/gtest/libgtest_main.a
- sudo make
- cd -

- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -U pavel-alyukaev:$BINTRAY_API_KEY "https://api.bintray.com/content/Pavel-Alyukaev/otus-hello-world/helloworld/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
